---

- name: Install Apache
  hosts: label_apache_latest
  remote_user: config
  tasks:
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
  - name: Wait for host
    wait_for:
      host: "{{ inventory_hostname }}"
      port: 22
      sleep: 20   
      timeout: 600
    delegate_to: localhost
  - name: Install httpd
    become: yes
    dnf:
      name: "httpd"
      state: latest
  - name: Enable and start httpd service
    become: yes
    systemd:
      name: httpd
      enabled: yes
      masked: no
      state: started